---
application:
  name: "show-and-tell-api"
  project: "show-and-tell"
  organization: "QoveryCommunity"
  storage:
  - name: "uploads"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/uploads"
routers:
- name: "main-show-and-tell-api"
  routes:
  - application_name: "show-and-tell-api"
    paths:
    - "/*"
