version: '3.4'

services:
  showandtellapi:
    image: showandtellapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 4000:4000
      - 8080:8080
